image: node:latest

cache:
  paths:
  - node_modules/

test:
    stage: test
    services:
        - postgres:9.6-alpine
    script:
        - npm install --include=dev
        - npm test

deploy_to_heroku:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=mealscout-server --api-key=$HEROKU_API_KEY
